library(boilerpipeR)
library(corpora)
library(RKEA)
library(RWeka)
library(skmeans)
library(SnowballC)
library(tau)
library(tm)
library(topicmodels)
library(wordcloud)
library(zipfR)
library(RTextTools)
library(dplyr)
library(cluster)
library(biclust)
library(ggplot2)
library(igraph)
library(fpc)

distances <- dist(mtdms, method="euclidean")
fit <- hclust(d=distances, method="ward.D")

plot(fit, hang=-1)
groups <- cutree(fit, k=4)
rect.hclust(fit, k=4, border="blue")

kfit <- kmeans(distances,8)
clusplot(as.matrix(distances),
         kfit$cluster, color=TRUE,
         shade=TRUE, labels=2, lines=0)

print(kfit$cluster[kfit$cluster==1])
print(kfit$cluster[kfit$cluster==2])
print(kfit$cluster[kfit$cluster==3])
print(kfit$cluster[kfit$cluster==4])
print(kfit$cluster[kfit$cluster==5])
print(kfit$cluster[kfit$cluster==6])
print(kfit$cluster[kfit$cluster==7])
print(kfit$cluster[kfit$cluster==8])